cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('',include('shop.urls',namespace='shop')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


payment/urls.py
from django.urls import path,re_path,include
from . import views

app_name='payment'

urlpatterns = [
    path('process/',views.create_order,name="process"),
    path('response/',views.payment_process,name="response"),
    # path('response/',views.response,name="response"),
    path('canceled/',views.payment_canceled,name="canceled"),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls'),name="paypal-ipn"),
    # re_path(r'^payment_process/$', api_views.payment_process, name='payment_process' ),

    # re_path(r'^payment_done/$', TemplateView.as_view(template_name= "pets/payment_done.html"), name='payment_done'),

    # re_path(r'^payment_canceled/$', TemplateView.as_view(template_name= "pets/payment_canceled.html"), name='payment_canceled'),
    

]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
# import braintree
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from orders.models import Order,OrderItem
from django.conf import settings

from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
import juspayp3 as Juspay
from random import randint
import json
import razorpay


client =razorpay.Client(auth=(settings.RAZORPAY_PUBLIC_KEY,settings.RAZORPAY_SECRET_KEY))
client.set_app_details({"title" : "Django", "version" : "1.8.17"})
amount=0
def create_order(request):
    order_id=request.session.get('order_id')
    order=get_object_or_404(Order,id=order_id)
    amount=int(order.get_total_cost()*100)
    amount_inr=amount//100
    print("Type amount ",amount)
    print("Type amount ",type(amount))
    print("Order is -> ",order)
    return render(request,'payment/created.html',{'order_id':order_id,'public_key':settings.RAZORPAY_PUBLIC_KEY,'amount':amount_inr,'amountorig':amount})

def payment_process(request):
    order_id=request.session.get('order_id')
    order=get_object_or_404(Order,id=order_id)
    print("Payment",order)
    if request.method=="POST":
        order.paid=True
        
        order.save()
        print("Payment order",order.paid)
        orderitem=get_object_or_404(OrderItem,order=order)
        print("Order Item",orderitem.get_cost())
        amount=int(orderitem.get_cost())*100
        amount_inr=amount//100
        print("Amount ",amount)
        print("Type amount str to int ",amount)
        payment_id=request.POST['razorpay_payment_id']
        order.braintree_id=payment_id
        order.save()
        # print("Multiple value",payment_id)
        print("Payment Id",payment_id)
        payment_client_capture=(client.payment.capture(payment_id,amount))    
        print("Payment Client capture",payment_client_capture)
        payment_fetch=client.payment.fetch(payment_id)
        status=payment_fetch['status']
        amount_fetch=payment_fetch['amount']
        amount_fetch_inr=amount_fetch//100
        print("Payment Fetch",payment_fetch['status'])
        return render(request,'payment/done.html',{'amount':amount_fetch_inr,'status':status})   

def payment_done(request):
    return render(request, 'payment/done.html',{})
 
 
def payment_canceled(request):
    return render(request, 'payment/canceled.html',{})

def response(request):
    res=dict()
    res['order_id']=request.GET.get('order_id')
    res['status']=request.GET.get('status')
    res['signature']=request.GET.get('signature')
    res['signature_algorithm'] = request.GET.get('signature_algorithm')
    print(res)
    return render(request,'payment/done.html',{'res':res})

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block content %}
 <h1>Your payment has not been processed</h1>
 <p>There was a problem processing your payment.</p>
{% endblock %}

payment/templates/payment/created.html
{% extends "shop/base.html" %}
{% block title %}
 Thank you
{% endblock %}
{% block content %}
 <h1>Thank you</h1>
 <p>Complete payment details to confirm order<br> Your order number is
 <strong>{{ order_id }}</strong><br>
 Your pay amount is <strong>{{ amount }}</strong> </p>
<form action="{% url 'payment:response' %}" method="POST">
{% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key={{public_key}}
    data-amount={{ amountorig }}
    data-buttontext="Pay with Razorpay"
    data-name="Online Shop"
    data-description=""
    data-image="https://your-awesome-site.com/your_logo.jpg"
    data-prefill.name="Sachin Siddhpura"
    data-prefill.email="test@test.com"
    data-theme.color="#F37254"
    data-notes.address="Rajkot"
></script>
<input type="hidden" value="Hidden Element" name="hidden">
</form>

{% endblock %}

payment/templates/payment/done.html
{% comment %} {% extends "shop/base.html" %} {% endcomment %}

{% block content %}
 <h1>Your payment was successful</h1>
 <p>Your payment has been processed successfully.</p>
{% endblock %}
<p>Your Order amount is <strong>{{amount}}</strong></p>

payment/templates/payment/process.html
{% comment %} {% extends 'shop/base.html' %}
{% block title %}Pay by credit cart {% endblock %}

{% block content %}
    <h1>Pay by credit card</h1>
    <form action="." id="payment" method="post">
        <label for="card-number">Card Number</label>
        <div id="card-number" class="field"></div>
        <label for="cvv">CVV</label>
        <div id="cvv" class="field"></div>
        <label for="expiration-date">Expiration Date</label>
        <div id="expiration-date" class="field"></div>
        <input type="hidden" id="nonce" name="payment_method_nonce" value="">
        {% csrf_token %}
        <input type="submit" value="pay">
    </form>    
    <!-- Load the required client component. -->
    <script src="https://js.braintreegateway.com/web/3.29.0/js/client.min.js"></script>
    <!-- Load Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.29.0/js/hosted-fields.min.js"></script>
    <script>
        var form=document.querySelector('#payment');
        var submit=document.querySelector('input[type="submit"]');
        braintree.client.create({
            authorization: '{{ client_token }}'
            }, function (clientErr, clientInstance) {
            if (clientErr) {
            console.error(clientErr);
            return;
            }
        braintree.hostedFields.create({
            client: clientInstance,
            styles: {
            'input': {'font-size': '13px'},
            'input.invalid': {'color': 'red'},
            'input.valid': {'color': 'green'}
            },
            fields: {
            number: {selector: '#card-number'},
            cvv: {selector: '#cvv'},
            expirationDate: {selector: '#expiration-date'}
            }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
            if (hostedFieldsErr) {
                console.error(hostedFieldsErr);
                return;
                }
                submit.removeAttribute('disabled');
                form.addEventListener('submit', function (event) {
                event.preventDefault();
                hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
                if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
                }
                // set nonce to send to the server
                document.getElementById('nonce').value = payload.nonce;
                // submit form
                document.getElementById('payment').submit();
                });
                }, false);
                });
                });
        </script>           
    
{% endblock %} {% endcomment %}
{% comment %} 
<h1>Pay using paypal</h1>
{{form.render }} {% endcomment %}
{% comment %} <p>{{order}}</p> {% endcomment %}
{% comment %} {% comment %} {{ links }} {% endcomment %}
{% comment %} <a href={{web}}>Pay Now</a> {% endcomment %}


{% comment %} Customize form {% endcomment %}

{% comment %} Cutomize form end {% endcomment %}
<!-- Note that the amount is in paise = 50 INR -->




{% comment %} default form {% endcomment %}
{% comment %} <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key={{public_key}}
    data-amount={{ amount }}
    data-buttontext="Pay with Razorpay"
    data-name="Merchant Name"
    data-description="Purchase Description"
    data-image="https://your-awesome-site.com/your_logo.jpg"
    data-prefill.name="Amit kadivar"
    data-prefill.email="test@test.com"
    data-theme.color="#F37254"
></script> {% endcomment %}
{% comment %} <input type="hidden" value="Hidden Element" name="hidden"> {% endcomment %}
{% comment %}  {% endcomment %}